"""Re-target document_chunks embeddings to voyage-4-lite (1024-dim).

Pinned model change (CLAUDE.md sections 2/13): gemini-embedding-001 (768-dim) is
replaced by the hosted Voyage embedding model voyage-4-lite at 1024-dim
(Matryoshka output pinned via output_dimension).  A stored 768-dim vector cannot be
cast to vector(1024) — the dimension is part of the pgvector type — and mixing models
in one index silently returns plausible-looking garbage rather than failing
(CLAUDE.md Risk 1).  The only correct action is to wipe the stored embeddings,
resize, rebuild the HNSW index, and re-embed every chunk from the preserved content.

This migration therefore:
1. drops the HNSW cosine index (pgvector forbids the type change while it exists),
2. nulls every embedding (column is temporarily nullable),
3. resizes the column to vector(1024),
4. recreates the HNSW index with the same parameters migration 0001 established.

The embedding column intentionally remains nullable after this migration: a
NOT NULL constraint cannot be restored while the rows are still NULL, and the
stored vectors must be regenerated by ``scripts/backfill_embeddings.py`` using
the new hosted Voyage model.  Until the backfill runs, every chunk carries a
NULL placeholder that scores 0.0 against every query — failing the Layer-1
grounding threshold and making the assistant refuse honestly instead of
answering from data it cannot measure (the safe state between wipe and
backfill).  Once the backfill has given every chunk a non-NULL 1024-dimensional
embedding it seals the invariant itself (restoring NOT NULL on the column);
no separate migration restores it, because any migration in this chain would
run on a still-null corpus the first time ``upgrade head`` is executed before
backfill.

Documents and chunk content are preserved; only the vectors are regenerated.

Revision ID: 0018_embedding_dim_1024
Revises: 0017_embedding_dim_768
"""

from alembic import op

revision = "0018_embedding_dim_1024"
down_revision = "0017_embedding_dim_768"
branch_labels = None
depends_on = None

_VECTOR_INDEX = "ix_document_chunks_embedding_hnsw"


def upgrade() -> None:
    # The index must go before the type change.
    op.execute(f"DROP INDEX IF EXISTS {_VECTOR_INDEX}")

    # Null then resize: vector(768) -> vector(1024) only succeeds through the
    # cast, which requires every value to be 1024-dimensional (or NULL). NOT NULL
    # is not restored here — every row is NULL at this point, and the backfill
    # script must be the component that repopulates and seals it.
    op.execute("ALTER TABLE document_chunks ALTER COLUMN embedding DROP NOT NULL")
    op.execute("UPDATE document_chunks SET embedding = NULL")
    op.execute("ALTER TABLE document_chunks ALTER COLUMN embedding TYPE vector(1024)")

    # HNSW needs no training pass and works on rows that arrive after it (0001/0008).
    op.execute(
        f"CREATE INDEX {_VECTOR_INDEX} ON document_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    # Mirror, and lose the 1024-dim vectors boundary like upgrade did: re-embedding
    # happens via the backfill script in either direction. The column stays
    # nullable, matching the post-upgrade state.
    op.execute(f"DROP INDEX IF EXISTS {_VECTOR_INDEX}")
    op.execute("ALTER TABLE document_chunks ALTER COLUMN embedding DROP NOT NULL")
    op.execute("UPDATE document_chunks SET embedding = NULL")
    op.execute("ALTER TABLE document_chunks ALTER COLUMN embedding TYPE vector(768)")
    op.execute(
        f"CREATE INDEX {_VECTOR_INDEX} ON document_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )